"""Request and response models for the public Insurance AI guide."""

from typing import Literal
from pydantic import BaseModel, Field


class GuideChatRequest(BaseModel):
    """A visitor message for the platform guide."""

    message: str = Field(min_length=1, max_length=1_500)


class DocumentChecklistItem(BaseModel):
    """One required claim document with its submission state."""

    name: str
    submitted: bool = False


class ClaimStatusData(BaseModel):
    """Structured claim status payload rendered as a card in the agent UI."""

    id: int
    claim_type: str
    status: str
    amount: float | None = None
    documents: list[DocumentChecklistItem] | None = None
    next_steps: list[str] | None = None


class PolicyInfoData(BaseModel):
    """Structured policy payload rendered as a card in the agent UI."""

    policy_number: str
    product_name: str
    status: str
    coverage_type: str | None = None
    end_date: str | None = None
    benefits: list[str] | None = None


class StructuredData(BaseModel):
    """Optional structured payload attached to a chat reply."""

    type: Literal["claim_status", "policy_info"]
    claims: list[ClaimStatusData] | None = None
    policies: list[PolicyInfoData] | None = None


class GuideChatResponse(BaseModel):
    """A concise, visitor-safe reply generated by the configured LLM."""

    reply: str
    mode: Literal["guest", "customer"] = "guest"
    actions: list[dict[str, str]] = Field(default_factory=list)
    structured_data: StructuredData | None = None


class ConsultationRequestCreate(BaseModel):
    """Contact details voluntarily submitted from the floating agent."""

    name: str = Field(min_length=2, max_length=180)
    email: str | None = Field(default=None, max_length=255)
    phone: str | None = Field(default=None, max_length=60)
    product_interest: str | None = Field(default=None, max_length=180)
    preferred_time: str | None = Field(default=None, max_length=180)
    question: str | None = Field(default=None, max_length=1_500)


class ConsultationRequestResponse(BaseModel):
    id: int
    status: str
    message: str
