"""Request and response models for the public Insurance AI guide."""

from typing import Literal
from pydantic import BaseModel, Field


class GuideChatRequest(BaseModel):
    """A visitor message for the platform guide."""

    message: str = Field(min_length=1, max_length=1_500)


class GuideChatResponse(BaseModel):
    """A concise, visitor-safe reply generated by the configured LLM."""

    reply: str
    mode: Literal["guest", "customer"] = "guest"
    actions: list[dict[str, str]] = Field(default_factory=list)


class ConsultationRequestCreate(BaseModel):
    """Contact details voluntarily submitted from the floating agent."""

    name: str = Field(min_length=2, max_length=180)
    email: str | None = Field(default=None, max_length=255)
    phone: str | None = Field(default=None, max_length=60)
    product_interest: str | None = Field(default=None, max_length=180)
    preferred_time: str | None = Field(default=None, max_length=180)
    question: str | None = Field(default=None, max_length=1_500)


class ConsultationRequestResponse(BaseModel):
    id: int
    status: str
    message: str
