import { useRef, useState } from "react";
import { useGSAP } from "@gsap/react";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import { Link } from "react-router-dom";
import { ArrowRightIcon, ClockIcon, DashboardIcon, FileTextIcon, LayersIcon, SearchIcon, ShieldCheckIcon, UserCheckIcon } from "../components/icons";

gsap.registerPlugin(useGSAP, ScrollTrigger);

const agents = [
  ["CP", "Claims Processing", "Reads incoming documents, extracts evidence, and prepares a complete claim file for review."],
  ["FD", "Fraud Detection", "Surfaces unusual patterns and conflicting evidence without making an adverse decision."],
  ["CS", "Customer Service", "Answers policy questions, explains status, and hands complex conversations to the right team."],
  ["UR", "Underwriting & Risk", "Structures submissions, highlights risk signals, and gives underwriters an evidence-led view."],
  ["PR", "Policy Review", "Compares policy wording, endorsements, and claim facts with traceable source references."],
  ["CB", "Compliance & CEO Briefing", "Turns operational and regulatory activity into concise, decision-ready leadership briefs."]
];
const demoSteps = [
  ["Intake understood", "Motor claim documents classified and key facts extracted.", "Complete"],
  ["Policy matched", "Coverage, exclusions, and limits linked to source clauses.", "Complete"],
  ["Risk signals checked", "One repair estimate variance flagged for an adjuster.", "Review"],
  ["Decision pack ready", "Evidence summary and audit trail prepared for approval.", "Ready"]
];

export function DashboardPage() {
  const pageRef = useRef<HTMLDivElement>(null);
  const [activeAgent, setActiveAgent] = useState(0);

  useGSAP(() => {
    if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) return;
    gsap.from(".landingHeroCopy > *", { opacity: 0, y: 26, duration: .85, stagger: .09, ease: "power3.out" });
    gsap.from(".heroProduct", { opacity: 0, scale: .9, y: 35, duration: 1.15, ease: "power3.out" });
    gsap.utils.toArray<HTMLElement>(".landingReveal").forEach((element) => gsap.fromTo(element, { opacity: .2, scale: .92, y: 44 }, { opacity: 1, scale: 1, y: 0, ease: "none", scrollTrigger: { trigger: element, start: "top 90%", end: "top 62%", scrub: true } }));
    gsap.utils.toArray<HTMLElement>(".workflowStep").forEach((card, index) => gsap.to(card, { y: index * -12, scrollTrigger: { trigger: card, start: "top 80%", end: "bottom 45%", scrub: true } }));
  }, { scope: pageRef });


  return <div className="insuranceLanding" ref={pageRef}>
    <section className="landingHero" aria-labelledby="landing-title">
      <div className="landingHeroCopy"><p className="landingEyebrow">One coordinated insurance intelligence layer</p><h1 id="landing-title">Insurance work,<br/><em>handled intelligently.</em></h1><p className="landingLead">Purpose-built AI agents help insurers move from intake to executive insight—faster, more consistently, and always with people in control.</p><div className="landingActions"><a className="landingButton primary" href="#consultation">Book a consultation <ArrowRightIcon size={17}/></a><a className="landingButton secondary" href="#product-demo">See the platform</a></div><div className="heroLines" aria-label="Supported insurance lines"><span>Health</span><span>Motor</span><span>Life</span><span>Property</span></div></div>
      <div className="heroProduct" aria-label="Coordinated insurance agent workspace"><div className="heroProductTop"><span>Live case orchestration</span><strong>IA-2048</strong></div><img src="/healthinsurance.avif" alt="Insurance professional reviewing a customer case"/><div className="heroProductFlow"><div><span className="pulseDot"/>Document intake</div><ArrowRightIcon size={16}/><div>Agent review</div><ArrowRightIcon size={16}/><div>Human decision</div></div><div className="heroProductNote"><ShieldCheckIcon size={20}/><span><strong>Human review required</strong>One risk signal needs confirmation</span></div></div>
    </section>
    <div className="trustStrip" aria-label="Platform principles"><div>{["Evidence-linked outputs","Role-based human review","Traceable audit history","Configurable business rules","Evidence-linked outputs","Role-based human review","Traceable audit history","Configurable business rules"].map((item,index)=><span key={`${item}-${index}`}><ShieldCheckIcon size={14}/>{item}</span>)}</div></div>
    <section className="painSection" id="solutions" aria-labelledby="pain-title"><div className="sectionIntro"><p className="landingEyebrow">The operational reality</p><h2 id="pain-title">Insurance teams do not need more dashboards. They need work to move.</h2></div><div className="painBento"><article className="painPrimary landingReveal"><div><ClockIcon size={30}/><h3>Complex cases wait between teams</h3><p>Documents, policy checks, risk signals, and customer updates often live in separate systems and queues.</p></div><strong>Hours of manual coordination become one governed flow.</strong></article><article className="painPanel painGreen landingReveal"><SearchIcon size={28}/><h3>Evidence is hard to trace</h3><p>Teams lose time searching for the source behind a value, clause, or recommendation.</p></article><article className="painPanel painSand landingReveal"><UserCheckIcon size={28}/><h3>Judgment must stay accountable</h3><p>Automation needs clear escalation, human ownership, and a complete record of every action.</p></article></div></section>
    <section className="agentSection" id="agents" aria-labelledby="agents-title"><div className="sectionIntro compact"><p className="landingEyebrow">A practical agent portfolio</p><h2 id="agents-title">Specialists for the work your teams already do.</h2><p>Start with one workflow or coordinate the complete portfolio across claims, service, underwriting, policy, fraud, and leadership reporting.</p></div><div className="agentAccordion">{agents.map(([code,name,copy],index)=><button key={code} type="button" className={activeAgent===index?"active":""} onClick={()=>setActiveAgent(index)} aria-expanded={activeAgent===index}><span className="agentCode">{code}</span><span className="agentDetails"><strong>{name} Agent</strong><small>{copy}</small></span><ArrowRightIcon size={18}/></button>)}</div></section>
    <section className="workflowSection" id="workflow" aria-labelledby="workflow-title"><div className="workflowIntro"><p className="landingEyebrow">One case, coordinated end to end</p><h2 id="workflow-title">Agents collaborate. Your team remains the decision-maker.</h2><p>Each specialist contributes a bounded task, passes structured evidence forward, and escalates uncertainty instead of hiding it.</p></div><div className="workflowStack">{["Understand","Investigate","Recommend","Approve"].map((title,index)=><article className="workflowStep" key={title}><span>{String(index+1).padStart(2,"0")}</span><div><h3>{title}</h3><p>{["Classify the request and connect documents to the right policy and customer.","Run policy, risk, fraud, and completeness checks against traceable evidence.","Prepare an explainable action pack with confidence, exceptions, and next steps.","Route to the authorized person, capture their decision, and preserve the audit trail."][index]}</p></div></article>)}</div></section>
    <section className="demoSection" id="product-demo" aria-labelledby="demo-title"><div className="sectionIntro demoIntro"><p className="landingEyebrow">Interactive product view</p><h2 id="demo-title">See the case, not the system noise.</h2><p>A clear workspace shows what the agents found, what needs attention, and exactly where a reviewer should step in.</p></div><div className="demoWindow landingReveal"><div className="demoNav"><span className="demoBrand"><LayersIcon size={18}/>Insurance AI</span><span className="demoCase">Motor claim · IA-2048</span><span className="demoStatus"><span/>Review ready</span></div><div className="demoBody"><aside><strong>Case workspace</strong>{["Overview","Evidence","Policy match","Risk signals","Audit history"].map((item,index)=><button className={index===0?"active":""} type="button" key={item}>{item}</button>)}</aside><div className="demoContent"><div className="demoHeading"><div><small>CASE SUMMARY</small><h3>Rear impact collision</h3><p>Four documents processed. Coverage confirmed. One estimate variance needs review.</p></div><div className="confidence"><strong>94%</strong><span>evidence confidence</span></div></div><div className="demoTimeline">{demoSteps.map(([title,detail,status])=><div key={title}><span className={status==="Review"?"review":"done"}>{status==="Review"?"!":"✓"}</span><div><strong>{title}</strong><p>{detail}</p></div><small>{status}</small></div>)}</div></div></div></div></section>
    <section className="benefitSection" aria-labelledby="benefit-title"><div className="sectionIntro"><p className="landingEyebrow">Measurable operating value</p><h2 id="benefit-title">Better throughput without trading away trust.</h2></div><div className="benefitGrid">{[["Faster","Move routine work automatically","Reduce handoffs and let specialists focus on exceptions and judgment."],["Clearer","Keep every output explainable","Link extracted values, policy clauses, and flags back to their evidence."],["Consistent","Apply the same rules every time","Configure workflows by product, market, authority level, and risk appetite."],["Scalable","Support every major insurance line","Use a shared platform across health, motor, life, and property operations."]].map(([value,title,copy])=><article key={value}><strong>{value}</strong><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
    <section className="safeguardSection" id="safeguards" aria-labelledby="safeguard-title"><div className="safeguardVisual"><div className="shieldRings"><ShieldCheckIcon size={54}/></div><div className="reviewCard"><span>Decision boundary</span><strong>Human approval required</strong><small>Confidence below configured threshold</small></div></div><div className="safeguardCopy"><p className="landingEyebrow">Designed for accountable automation</p><h2 id="safeguard-title">AI assists. Authorized people decide.</h2><p>Every agent operates within a defined role. Low confidence, conflicting evidence, sensitive outcomes, and policy exceptions are routed for review.</p><ul><li><ShieldCheckIcon size={19}/>Configurable approval thresholds and authority levels</li><li><FileTextIcon size={19}/>Evidence citations and immutable action history</li><li><UserCheckIcon size={19}/>Clear ownership, escalation, and reviewer controls</li><li><DashboardIcon size={19}/>Operational and executive reporting without black-box conclusions</li></ul></div></section>
    <section className="operationsSection" aria-labelledby="operations-title"><div><p className="landingEyebrow">Customer claims portal</p><h2 id="operations-title">Your policy. Your claim. One guided flow.</h2><p>Sign in to view policies, start a claim, upload evidence, and follow status. Personal claim tools stay private.</p></div><Link className="landingButton primary" to="/login">Sign in to continue <ArrowRightIcon size={16}/></Link></section>
    <section className="finalCta" id="consultation" aria-labelledby="cta-title"><div><p className="landingEyebrow">Build the right first workflow</p><h2 id="cta-title">Put an Insurance AI Agent to work.</h2><p>Start with the operational bottleneck that matters most, then expand on one governed platform.</p></div><div className="landingActions"><a className="landingButton light" href="mailto:hello@example.com?subject=Insurance%20AI%20consultation">Book a consultation <ArrowRightIcon size={17}/></a><Link className="landingButton outline" to="/login">Customer sign in</Link></div></section>
    <footer className="landingFooter"><div className="footerBrand"><span><ShieldCheckIcon size={22}/></span><div><strong>Insurance AI Agent</strong><small>Practical intelligence for modern insurers</small></div></div><div className="footerLinks"><a href="#agents">Agents</a><a href="#workflow">How it works</a><a href="#safeguards">Safeguards</a><Link to="/officer">Officer portal</Link></div><p>© 2026 Insurance AI Agent. Built for accountable insurance operations.</p></footer>
  </div>;
}
